ead:
  service-registry:
    username: serviceregistryclientprod
    password: '{cipher}02b3372fd9d41d136cfaf4c9c53928a2073fb79e0e9e680b575ebad12d409ae1'
  auth:
    jwt-secret: '{cipher}B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s5v'
    jwt-expiration-ms: 7200000
eureka:
  client:
    service-url:
      defaultZone: 'https://serviceregistryclientprod:GVitjsOx1M@ead-serviceregistry-prd.herokuapp.com/eureka'
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80


