ead:
  service-registry:
    username: serviceregistryclient
    password: 'secretead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


