ead:
  service-registry:
    username: serviceregistryclient
    password: 'secretead123sr'
  auth:
    jwt-secret: !z%C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4
    jwt-expiration-ms: 7200000
eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


